"""
sign.py — Stage 4: Dilithium Bitstream Signing (SHIPP Pipeline)
================================================================
Takes the final bitstream produced by Stage 1-3 of minutiae extraction
(encoding.generate_final_bitstream → stats['bitstream']), converts it to
bytes, and signs it using the ML-DSA-65 private key generated by Stage 3
(keygen.py).

Bitstream source (confirmed from encoding.py):
    encoding.generate_final_bitstream(sorted_minutiae)
        → dict with key 'bitstream': str of '0'/'1' characters
        → dict with key 'total_bits': int length of that string

Padding scheme:
    Bitstream lengths vary per image (e.g. 728, 1036, 1400 bits).
    To convert to bytes, zero-bits are appended at the RIGHT (LSB side)
    until len(bitstring) % 8 == 0.
        padding_bits = (8 - len(bitstring) % 8) % 8
    The original bit-length is stored alongside the signature so the
    padding can be stripped losslessly on verification.

Dependency:
    liboqs-python 0.16.0+  (pip install liboqs-python)
    The native shared library (liboqs.dll / liboqs.so) must be on PATH.
    Run keygen.py first to generate keys/dilithium_private.key.
"""

import os
import sys
import time
import hashlib
import argparse

# Pipeline modules (same source of truth as main.py)
import preprocessing
import thinning
import minutiae as minutiae_mod
import encoding

# Stage 3 key management
import keygen

# --- Configuration ----------------------------------------------------------

SIGNATURES_DIR = "signatures"
ALGORITHM      = keygen.ALGORITHM   # "ML-DSA-65" — kept in one place

# --- Dependency guard --------------------------------------------------------

def _import_oqs():
    """Import oqs with a clear, actionable error message if unavailable."""
    try:
        import oqs
        return oqs
    except ImportError:
        raise ImportError(
            "liboqs-python is not installed.\n"
            "  Install with:  pip install liboqs-python\n"
            "  Then ensure the native shared library (liboqs.dll / liboqs.so)\n"
            "  is on your PATH / LD_LIBRARY_PATH before running this script."
        )
    except OSError as exc:
        raise OSError(
            "liboqs-python is installed but the native shared library could not be loaded.\n"
            f"  Underlying error: {exc}\n"
            "  On Windows: set PATH=C:\\path\\to\\liboqs\\build\\bin;%PATH%"
        )

# --- Bitstream utilities -----------------------------------------------------

def bitstring_to_bytes(bitstring: str) -> tuple[bytes, int]:
    """
    Convert a '0'/'1' character string to a bytes object.

    Padding scheme
    --------------
    Zero-bits are appended at the RIGHT (least-significant side) to reach
    the nearest byte boundary:
        padding_bits = (8 - len(bitstring) % 8) % 8

    The caller is responsible for storing 'padding_bits' alongside the
    resulting bytes so the padding can be stripped on the receiving end.

    Parameters
    ----------
    bitstring : str
        A string of '0' and '1' characters (output of encoding.generate_final_bitstream).

    Returns
    -------
    data : bytes
        The padded bitstring packed into bytes (big-endian, MSB first).
    padding_bits : int
        Number of zero-bits appended (0–7).
    """
    padding_bits = (8 - len(bitstring) % 8) % 8
    padded       = bitstring + '0' * padding_bits
    # Pack 8 characters at a time into one byte (MSB first)
    data = bytes(int(padded[i:i+8], 2) for i in range(0, len(padded), 8))
    return data, padding_bits

# --- Pipeline wrapper --------------------------------------------------------

def extract_bitstream(image_path: str) -> tuple[str, int]:
    """
    Run the full SHIPP minutiae extraction pipeline for one image and return
    the final bitstream.

    This calls the same function chain used by main.run_pipeline():
        preprocessing → thinning → minutiae → encoding.generate_final_bitstream

    Parameters
    ----------
    image_path : str
        Path to the input fingerprint image.

    Returns
    -------
    bitstream : str
        The '0'/'1' string from encoding.generate_final_bitstream → stats['bitstream'].
    total_bits : int
        stats['total_bits'] — length of the bitstream before padding.

    Raises
    ------
    FileNotFoundError
        If the image file does not exist.
    """
    if not os.path.exists(image_path):
        raise FileNotFoundError(
            f"Image not found: '{image_path}'\n"
            "  Run Stage 1-2 first: python main.py --image <path>"
        )

    img      = preprocessing.load_grayscale_image(image_path)
    img_norm = preprocessing.normalize_image(img)
    img_eq   = preprocessing.histogram_equalization(img_norm)
    binary   = preprocessing.binarize_local_mean_manual(img_eq, window_size=15, constant=10)
    skeleton = thinning.zhang_suen_thinning(binary)

    all_m    = minutiae_mod.compute_crossing_number(skeleton)
    mask     = minutiae_mod.create_eroded_foreground_mask(binary, erode_size=20)
    pruned   = minutiae_mod.prune_minutiae(all_m, skeleton, mask, dist_threshold=10)
    oriented = minutiae_mod.compute_minutiae_orientations(pruned, skeleton)
    sorted_m = encoding.sort_minutiae_row_major(oriented)

    # This is the exact same call as main.py line 68
    stats = encoding.generate_final_bitstream(sorted_m)

    return stats['bitstream'], stats['total_bits']

# --- Signing -----------------------------------------------------------------

def sign_bitstream(bitstream_str: str, private_key: bytes) -> tuple[bytes, int, float, str]:
    """
    Convert the bitstream string to bytes and sign it with ML-DSA-65.

    Parameters
    ----------
    bitstream_str : str
        The '0'/'1' bitstream string from encoding.generate_final_bitstream.
    private_key : bytes
        The ML-DSA-65 private key loaded from keys/dilithium_private.key.

    Returns
    -------
    signature : bytes
        The raw Dilithium signature bytes.
    padding_bits : int
        Number of zero-bits appended before signing (needed for verification).
    elapsed_ms : float
        Wall-clock signing time in milliseconds.
    sha256_hex : str
        SHA-256 hash of the padded byte payload (for traceability).

    Notes
    -----
    oqs.Signature.sign() applies Dilithium's internal hashing (SHAKE-256
    based), so the bitstream length does not need to be fixed — arbitrary
    byte inputs are accepted.
    """
    oqs = _import_oqs()

    payload, padding_bits = bitstring_to_bytes(bitstream_str)
    sha256_hex = hashlib.sha256(payload).hexdigest()

    t_start = time.perf_counter()
    with oqs.Signature(ALGORITHM, secret_key=private_key) as signer:
        signature = signer.sign(payload)
    elapsed_ms = (time.perf_counter() - t_start) * 1000

    return signature, padding_bits, elapsed_ms, sha256_hex

# --- Persistence -------------------------------------------------------------

def signature_filename(image_path: str) -> str:
    """
    Build the output filename for a signature, associated with the source image.
    Example: input_images/3.jpg → signatures/3_signature.bin
    """
    stem = os.path.splitext(os.path.basename(image_path))[0]
    return os.path.join(SIGNATURES_DIR, f"{stem}_signature.bin")


def save_signature(signature: bytes, image_path: str,
                   original_bits: int, padding_bits: int) -> str:
    """
    Save the signature and its metadata to the signatures/ directory.

    Two files are written per image:
        <stem>_signature.bin   — raw signature bytes
        <stem>_signature.meta  — plain-text metadata (original_bits, padding_bits)

    Parameters
    ----------
    signature : bytes
    image_path : str
    original_bits : int
        The unpadded bitstream length (for padding-strip on verification).
    padding_bits : int

    Returns
    -------
    sig_path : str
        Path of the saved signature file.
    """
    os.makedirs(SIGNATURES_DIR, exist_ok=True)
    sig_path  = signature_filename(image_path)
    meta_path = sig_path.replace("_signature.bin", "_signature.meta")

    with open(sig_path, "wb") as f:
        f.write(signature)

    with open(meta_path, "w") as f:
        f.write(f"source_image={os.path.basename(image_path)}\n")
        f.write(f"algorithm={ALGORITHM}\n")
        f.write(f"original_bits={original_bits}\n")
        f.write(f"padding_bits={padding_bits}\n")
        f.write(f"signature_bytes={len(signature)}\n")

    return sig_path

# --- High-level entry point --------------------------------------------------

def sign_image(image_path: str) -> dict:
    """
    Full Stage 4 flow for one image:
        extract bitstream → load private key → sign → save signature

    Returns a summary dict suitable for display or downstream use.
    """
    # 1. Extract bitstream via the same pipeline chain as main.py
    print(f"[*] Extracting bitstream from: {image_path}")
    bitstream_str, total_bits = extract_bitstream(image_path)

    # 2. Load private key generated by keygen.py (Stage 3)
    try:
        _, private_key = keygen.load_keys()
    except FileNotFoundError:
        raise FileNotFoundError(
            f"Private key not found at '{keygen.PRIV_KEY_FILE}'.\n"
            "  Run Stage 3 first: python keygen.py"
        )

    # 3. Sign
    print(f"[*] Signing {total_bits}-bit bitstream with {ALGORITHM}...")
    signature, padding_bits, elapsed_ms, sha256_hex = sign_bitstream(bitstream_str, private_key)

    # 4. Persist
    sig_path = save_signature(signature, image_path, total_bits, padding_bits)
    print(f"[+] Signature saved → {sig_path}")

    payload_bytes = (total_bits + padding_bits) // 8

    return {
        'image_path':    image_path,
        'total_bits':    total_bits,
        'padding_bits':  padding_bits,
        'payload_bytes': payload_bytes,
        'sha256':        sha256_hex,
        'sig_bytes':     len(signature),
        'sig_bits':      len(signature) * 8,
        'elapsed_ms':    elapsed_ms,
        'sig_path':      sig_path,
    }

# --- __main__ ----------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="SHIPP Stage 4 — Sign fingerprint bitstream with Dilithium (ML-DSA-65)."
    )
    parser.add_argument(
        "--image",
        type=str,
        default="input_images/3.jpg",
        help="Path to the fingerprint image to sign (default: input_images/3.jpg)"
    )
    args = parser.parse_args()

    print("=" * 65)
    print("SHIPP Pipeline — Stage 4: Dilithium Bitstream Signing")
    print("=" * 65)

    result = sign_image(args.image)

    col = 26
    print()
    print("=" * 65)
    print("SIGNING SUMMARY")
    print("=" * 65)
    print(f"  {'Source image':<{col}}: {result['image_path']}")
    print(f"  {'Algorithm':<{col}}: {ALGORITHM}")
    print(f"  {'Bitstream length':<{col}}: {result['total_bits']} bits")
    print(f"  {'Padding appended':<{col}}: {result['padding_bits']} bits  "
          f"(right zero-padding to nearest byte)")
    print(f"  {'Payload size':<{col}}: {result['payload_bytes']} bytes  "
          f"({result['payload_bytes'] * 8} bits)")
    print(f"  {'SHA-256 of payload':<{col}}: {result['sha256']}")
    print(f"  {'Signing time':<{col}}: {result['elapsed_ms']:.2f} ms")
    print(f"  {'Signature size':<{col}}: {result['sig_bytes']} bytes  "
          f"({result['sig_bits']} bits)")
    print(f"  {'Signature file':<{col}}: {os.path.abspath(result['sig_path'])}")
    print("=" * 65)
